baseURL = 'https://rohankumar.me/'
languageCode = 'en-us'
publishDir = 'docs'
theme = 'archie'
title = 'Rohan Kumar'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
customcss = ["css/main.css"]
mode = "toggle"
subtitle = "Hi, I'm Rohan."
useCDN = false

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/rohankmr414"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/rohankmr414/"

[[params.social]]
icon = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/rohankmr414/"

# Main menu Items

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 1
